### ISSUE TITLE
Internal Server Error When Adding Vendor Price Inside Product

### ISSUE THREAD

**Issue by harshqa-webkul** [aureuserp/aureuserp#293]
## Description:
When trying to add a Vendor Price inside a product, the system throws an Internal Server Error instead of successfully saving the vendor price.

## Actual Result:
An Internal Server Error occurs when adding a Vendor Price inside the product.

## Expected Result:
The Vendor Price should be added successfully without any errors.
If any validation is required, the system should display a proper validation message instead of an error.

## Step to Produce:
1. Go to 'Purchase -> Products -> Create product'
2. Go to 'Vendors -> Add new Vendors Price -> click create'
3. See Error

## Screen Recording

https://github.com/user-attachments/assets/96c6a02a-b20a-4e7d-b09b-95c85b83c34c

**Comment by jitendra-webkul** [comment]
Fixed in #298

**Comment by harshqa-webkul** [comment]
Issue (Internal Server Error When Adding Vendor Price Inside Product) is still **not resolved**. The error persists when trying to add a vendor price. 

**Screen Recording**

https://github.com/user-attachments/assets/c8cc8766-466c-45ea-a92c-9b699d5e7f2c

**Comment by jitendra-webkul** [comment]
Fixed in #302

**Comment by harshqa-webkul** [comment]
This issue has been fixed **successfully** adding the vendor price without Errors

**Screen Shot**
https://prnt.sc/Ma8qorI6c6Ei
