### ISSUE TITLE
Destination Package ID Displayed Instead of Name in Manage Stock Lines Before Receipt Validation

### ISSUE THREAD

**Issue by harshqa-webkul** [aureuserp/aureuserp#351]
## Description:
In the Manage Stock Lines section, the system displays the destination package ID instead of the package name before validating the receipt.

## Actual Result:
The destination package field shows the ID (e.g., 5) instead of the human-readable name of the package.

## Expected Result:
The destination package field should display the name of the package (e.g., Box A, Container X) for better readability and user experience.

## Step to Reproduce:
1. Go to 'Inventory -> Operations -> Create Receipt -> Mark as Read'
2. Go to Under Product Quantity 'Manage Stock Moves' -> add Lines 
3. Click on '+' in Destination Package with Name and select any Location 
4. Click Create
5. See Destination Package ID instead of name  

## Screen Recording
https://github.com/user-attachments/assets/e5dd3146-64c3-41d1-9f23-7113a27c0618

**Comment by jitendra-webkul** [comment]
Fixed in #363

**Comment by harshqa-webkul** [comment]
Issue (Destination Package ID Displayed Instead of Name in Manage Stock Lines Before Receipt Validation) still persists ❌. The ID is shown instead of the expected package name. 

**Step to Reproduce**
1. Go to 'Inventory -> Operations -> Create Receipt -> Mark as Read'
2. Go to Under Product Quantity 'Manage Stock Moves' -> add Lines
3. Click on '+' in Destination Package with Name and select any Location other than (Location Type: Internal Location)
4. Click Create
5. See Destination Package ID instead of name


**Screen Recording**

https://github.com/user-attachments/assets/dfdaa6b5-6287-4bbf-b8fe-6523a29d398d

**Comment by jitendra-webkul** [comment]
Duplicate of #306
